### ISSUE TITLE
Unexpected Output for my code

### ISSUE THREAD

**Issue by raghulsivashanmugam-dev** [yuva-learn/home#2]
```dart
void main() {
  int count = 0;
  int num = 5;
  String tmp = "";
  
  for(int i = 1 ; i < num + 1 ; i++){
    for(int j = num - i ; 0 < j ; j--){
      tmp = tmp + " ";
    }
    for(int k = i + count ; k > 0 ; k--){
      tmp = tmp + "#";
    }
    print(tmp);
    count++;
  }
}
```
![image](https://user-images.githubusercontent.com/76088774/102475259-ab116400-407f-11eb-99d9-9f6e41cc99db.png)

Excepted Output:

            #
         # # #
      # # # # #

**Comment by yuva-dev** [comment]
You have the reset the `tmp=""` after every loop else the residue of previous loop is also printed.
```dart
void main() {
  int count = 0;
  int num = 5;
  
  
  for(int i = 1 ; i < num + 1 ; i++){
    String tmp = "";
    for(int j = num - i ; 0 < j ; j--){
      tmp = tmp + " ";
    }
    for(int k = i + count ; k > 0 ; k--){
      tmp = tmp + "#";
    }
    print(tmp);
    count++;
  }
}
```

Here is your out put
![image](https://user-images.githubusercontent.com/16523925/102476966-c2515100-4081-11eb-9333-0c517ff50a68.png)
